"""empty message

Revision ID: 2a9435901e6d
Revises: 
Create Date: 2018-10-12 14:36:05.898902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9435901e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msatoshi', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('quoted_currency', sa.String(length=3), nullable=True),
    sa.Column('quoted_amount', sa.String(length=30), nullable=True),
    sa.Column('rhash', sa.String(length=128), nullable=False),
    sa.Column('payreq', sa.String(length=256), nullable=False),
    sa.Column('pay_index', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.Integer(), nullable=False),
    sa.Column('msatoshi_received', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('meta', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rhash')
    )
    op.create_table('invoice_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('resp_code', sa.Integer(), nullable=True),
    sa.Column('resp_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_webhook')
    op.drop_table('invoice')
    # ### end Alembic commands ###
